### ISSUE TITLE
12_As an administrator, I need to see the of archived announcements

### ISSUE THREAD

**Issue by saro0h** [poledev/hubert#14]
_URL_ :            ``/backend?status=archived``
_Authentication_ : User has to be authenticated as an admin.

--------------------------------------------------------

Acceptance criteria
-------------------

- [x] The list must display only archived announcements

- [x] The list is by default sorted by the __Created at__ field of jobs

The list must contain those columns : 
- [x] __Company__
- [x] __Title__
- [x] __Created at__        (date of creation of the announcement, format JJ/MM/YYYY)
- [x] __List Displays__   (Number of views of the announcement from the list)
- [x] __View Displays__  (Number of views of the announcement from its page)
- [x] __Ext Displays__    (Number of views of the announcement from the API)
- [x] __Actions__
    - Edit
    - Delete

- [x] When the administrator clicks on __Company__ header of the table, it is filtered by __Company__

- [x] When the administrator clicks on __Title__ header of the table, it is filtered by __Title__

- [x] When the administrator clicks on __Created at__ header of the table, it is filtered by __Created at__

- [x] When the administrator clicks on __Edit__, he is redirected to the edit form of the job

- [x] When the administrator clicks on __Delete__, the job announcement is deleted.
    - __Constraint__ : a job announcement can’t be deleted if it’s archived. A message has to be displayed to the administrator « You cannot delete %job.title%, it must not be archived » 

- [x] The list must be paginated : 1 page = 25 announcements 

--------------------------------------------------------

List of archived announcements
------------------------------

![capture decran 2014-01-03 a 13 51 37](https://f.cloud.github.com/assets/667519/1896161/62a70f92-7b85-11e3-899c-ac4cdc0f87c7.png)

**Comment by Jean-Beru** [comment]
Complexity: 8 (2 if US10 is done)
