### ISSUE TITLE
10_As an administrator, I need to see the list of published announcement

### ISSUE THREAD

**Issue by saro0h** [poledev/hubert#3]
_URL_ :            ``/backend``
_Authentication_ : User has to be authenticated as an admin.

--------------------------------------------------------

Acceptance criteria
-------------------

- [x] The list must display only published announcements.

- [x] The list is by default sorted by the __Created at__ field of jobs

The list must contain those columns : 
- [x] __Company__
- [x] __Title__
- [x] __Created at__      (date of creation of the announcement, format JJ/MM/YYYY)
- [x] __List Displays__   (Number of views of the announcement from the list)
- [x] __View Displays__   (Number of views of the announcement from its page)
- [x] __Ext Displays__    (Number of views of the announcement from the API)
- [x] __Actions__
        Edit
        Delete

- [x] When the administrator clicks on __Company__ header of the table, it is filtered by __Company__

- [x] When the administrator clicks on __Title__ header of the table, it is filtered by __Title__

- [x] When the administrator clicks on __Created at__ header of the table, it is filtered by __Created at__

- [x] When the administrator clicks on __Edit__, he is redirected to the edit form of the job

- [x] When the administrator clicks on __Delete__, the job announcement is deleted
    - __Constraint__: a job announcement can’t be deleted if it’s published. A message has to be displayed to the administrator «``You cannot delete %job.title%, it must not be published``» 

- [x] The list must be paginated : 1 page = 25 announcements 

--------------------------------------------------------

List of published announcements
-------------------------------

![capture decran 2014-01-03 a 13 55 50](https://f.cloud.github.com/assets/667519/1896135/8758e3ae-7b82-11e3-8aad-079785299168.png)

Header of list sorted by Company
--------------------------------

![capture decran 2014-01-03 a 11 42 41](https://f.cloud.github.com/assets/667519/1896136/a1912506-7b82-11e3-8a06-f685d1246e6b.png)

Header of list sorted by Title
------------------------------

![capture decran 2014-01-03 a 11 43 12](https://f.cloud.github.com/assets/667519/1896139/b5dfdd90-7b82-11e3-8f7a-f43bb4f0cad2.png)

Header of list sorted by Created at
-----------------------------------

![capture decran 2014-01-03 a 11 43 44](https://f.cloud.github.com/assets/667519/1896141/ccc90d42-7b82-11e3-87ee-d39df86591ae.png)

**Comment by Jean-Beru** [comment]
Complexity: 8
